# These settings are used by the Python functions open_sdg_build() and
# open_sdg_check(), from sdg-build.

# List of languages.
languages:
  - en
  - it

# Where the data gets built.
site_dir: _build

# The file to use for the metadata schema.
schema_file: _prose.yml

# The parent folder of the 'meta' and 'data' folders.
src_dir: ''

# Links to Git repositories with translation data.
translations:
  - https://github.com/mauromussin/translations-open-sdg.git@1.0.0-rc8
  - https://github.com/mauromussin/translations-un-sdg.git@1.0.0-rc3

